// AUTO-GENERATED from schema/vocab/v1/*.yaml by make gen —— 禁止手改。
// 词表演进规则见 schema/AGENTS.md：enum 只允许追加，废弃用 deprecated/replaced_by。

/** 词表清单（schema/vocab/v1/*.yaml 文件名，不含后缀） */
export const VOCAB_FILES = [
  "action",
  "audio_role",
  "beat_role",
  "camera_motion",
  "compliance_risk",
  "copy_function",
  "defect_type",
  "mood",
  "negative_space",
  "overlay_intent",
  "proof_type",
  "remedy_action",
  "scene.food",
  "season",
  "shot_type",
  "subject.food",
  "ttl_class",
] as const;
export type VocabName = (typeof VOCAB_FILES)[number];

// ── 枚举值（id 元组 + 字面量类型） ─────────────────────────────

/** action（37 值） */
export const action = [
  "CUT",
  "WASH",
  "MARINATE",
  "STIR",
  "POUR",
  "SPRINKLE",
  "SEASON",
  "WRAP",
  "ROLL",
  "KNEAD",
  "STIR_FRY",
  "DEEP_FRY",
  "STEAM",
  "BOIL",
  "GRILL",
  "SIMMER",
  "PLATE",
  "GARNISH",
  "LIFT",
  "OPEN_LID",
  "STEAM_RISE",
  "SERVE",
  "PACK",
  "TAKE_ORDER",
  "CHECKOUT",
  "UNBOX",
  "WEIGH",
  "SMILE",
  "WAVE",
  "POINT",
  "RECOMMEND",
  "THUMBS_UP",
  "EAT",
  "DRINK",
  "REACT_SURPRISE",
  "QUEUE",
  "WALK_THROUGH",
] as const;
export type Action = (typeof action)[number];

/** audio_role（4 值） */
export const audioRole = ["VO", "SYNC", "SILENT", "SFX"] as const;
export type AudioRole = (typeof audioRole)[number];

/** beat_role（7 值，冻结） */
export const beatRole = [
  "HOOK",
  "CONTEXT",
  "PROOF",
  "CONTRAST",
  "OFFER",
  "CTA",
  "BUMPER",
] as const;
export type BeatRole = (typeof beatRole)[number];

/** camera_motion（9 值） */
export const cameraMotion = [
  "STATIC",
  "PUSH",
  "PULL",
  "PAN",
  "TILT",
  "TRACK",
  "HANDHELD",
  "ORBIT",
  "WHIP",
] as const;
export type CameraMotion = (typeof cameraMotion)[number];

/** compliance_risk（16 值） */
export const complianceRisk = [
  "AD_LAW_SUPERLATIVE",
  "AD_LAW_UNPROVEN_CLAIM",
  "MEDICAL_CLAIM",
  "FINANCIAL_PROMISE",
  "PRICE_FRAUD",
  "MISSING_QUALIFICATION",
  "REQUIRED_DISCLAIMER_MISSING",
  "PORTRAIT_RIGHT",
  "VOICE_RIGHT",
  "TRADEMARK",
  "MUSIC_LICENSE",
  "THIRD_PARTY_CONTENT",
  "AIGC_LABEL_REQUIRED",
  "AI_FACE_MISUSE",
  "FACT_STALE",
  "FACT_UNVERIFIABLE",
] as const;
export type ComplianceRisk = (typeof complianceRisk)[number];

/** copy_function（18 值） */
export const copyFunction = [
  "QUESTION_HOOK",
  "NUMBER_HOOK",
  "COUNTERINTUITIVE_HOOK",
  "SCENE_HOOK",
  "RESULT_FIRST",
  "PAIN_CALLOUT",
  "ORIGIN_STORY",
  "CRAFT_STORY",
  "PERSONA_STORY",
  "TESTIMONY_QUOTE",
  "DATA_CITE",
  "OBJECTION_RESPOND",
  "COMPARISON",
  "SCARCITY",
  "OFFER_CLAIM",
  "DIRECTION_CTA",
  "LOCATION_CUE",
  "SLOGAN",
] as const;
export type CopyFunction = (typeof copyFunction)[number];

/** defect_type（39 值） */
export const defectType = [
  "BLURRY",
  "SHAKE",
  "OVEREXPOSED",
  "UNDEREXPOSED",
  "FLICKER",
  "BLACK_FRAME",
  "FREEZE_FRAME",
  "AUDIO_CLIPPING",
  "AUDIO_TOO_QUIET",
  "NOISY_AUDIO",
  "SILENT_AUDIO",
  "RESOLUTION_LOW",
  "ASPECT_MISMATCH",
  "SUBJECT_MISSING",
  "SUBJECT_TOO_SMALL",
  "SUBJECT_TRUNCATED",
  "WRONG_SHOT_TYPE",
  "WRONG_MOTION",
  "BAD_FRAMING",
  "NEGATIVE_SPACE_MISSING",
  "OBSTRUCTED",
  "BACKGROUND_CLUTTER",
  "HANDLES_MISSING",
  "DURATION_SHORT",
  "WRONG_SCENE",
  "LIPSYNC_OFF",
  "FACE_WARP",
  "HAND_WARP",
  "TEXT_WARP",
  "TEMPORAL_WARP",
  "PLASTIC_LOOK",
  "IDENTITY_DRIFT",
  "THIRD_PARTY_FACE",
  "THIRD_PARTY_LOGO",
  "BANNED_TERM",
  "CLAIM_WITHOUT_PROOF",
  "LICENSE_MUSIC_MISSING",
  "AIGC_LABEL_MISSING",
  "PORTRAIT_AUTH_MISSING",
] as const;
export type DefectType = (typeof defectType)[number];

/** mood（8 值） */
export const mood = [
  "WARM",
  "ENERGETIC",
  "COZY",
  "FRESH",
  "APPETIZING",
  "PROFESSIONAL",
  "PLAYFUL",
  "CALM",
] as const;
export type Mood = (typeof mood)[number];

/** negative_space（5 值） */
export const negativeSpace = [
  "TOP",
  "BOTTOM",
  "LEFT",
  "RIGHT",
  "NONE",
] as const;
export type NegativeSpace = (typeof negativeSpace)[number];

/** overlay_intent（14 值） */
export const overlayIntent = [
  "EMPHASIZE_NUMBER",
  "EMPHASIZE_KEYWORD",
  "KARAOKE_CAPTION",
  "STATIC_CAPTION",
  "ANNOTATE_PART",
  "ANNOTATE_PROOF",
  "PROGRESS_STEPS",
  "COUNTDOWN",
  "PRICE_TAG",
  "OFFER_BADGE",
  "LOCATION_CARD",
  "LOGO_WATERMARK",
  "AIGC_DISCLOSURE",
  "SUBTITLE_FOREIGN",
] as const;
export type OverlayIntent = (typeof overlayIntent)[number];

/** proof_type（8 值） */
export const proofType = [
  "LIVE_DEMO",
  "CUSTOMER_TESTIMONY",
  "QUALIFICATION",
  "DATA",
  "BEFORE_AFTER",
  "SOURCE_TRACE",
  "CRAFT_DETAIL",
  "SCENE_ATMOSPHERE",
] as const;
export type ProofType = (typeof proofType)[number];

/** remedy_action（15 值） */
export const remedyAction = [
  "RESHOOT",
  "REGENERATE",
  "RE_CROP",
  "RECOLOR",
  "AUDIO_FIX",
  "REPLACE_SHOT",
  "TRIM",
  "SPEED_ADJUST",
  "REWRITE_COPY",
  "MUTE_AUDIO",
  "BLUR_MASK",
  "ADD_DISCLAIMER",
  "ADD_LABEL",
  "RE_ORDER",
  "REJECT_SOURCE",
] as const;
export type RemedyAction = (typeof remedyAction)[number];

/** scene.food（14 值） */
export const sceneFood = [
  "STOREFRONT",
  "ENTRANCE",
  "NEIGHBORHOOD",
  "OUTDOOR_SEATING",
  "COUNTER",
  "DELIVERY_COUNTER",
  "DINING_AREA",
  "PRIVATE_ROOM",
  "OPEN_KITCHEN",
  "KITCHEN",
  "PREP_STATION",
  "WASH_STATION",
  "STORAGE",
  "SUPPLIER_ARRIVAL",
] as const;
export type SceneFood = (typeof sceneFood)[number];

/** season（6 值） */
export const season = [
  "ALL",
  "SPRING",
  "SUMMER",
  "AUTUMN",
  "WINTER",
  "FESTIVAL",
] as const;
export type Season = (typeof season)[number];

/** shot_type（8 值） */
export const shotType = [
  "EXTREME_CLOSEUP",
  "CLOSEUP",
  "MEDIUM",
  "WIDE",
  "OTS",
  "TABLETOP",
  "POV",
  "INSERT",
] as const;
export type ShotType = (typeof shotType)[number];

/** subject.food（24 值） */
export const subjectFood = [
  "OWNER",
  "CHEF",
  "STAFF",
  "CUSTOMER",
  "REGULAR_CUSTOMER",
  "COURIER",
  "HANDS",
  "SIGNAGE",
  "MENU_BOARD",
  "QUALIFICATION_CERT",
  "RECEIPT",
  "DISH_FINISHED",
  "DISH_PLATING",
  "INGREDIENT_RAW",
  "INGREDIENT_PREPPED",
  "MEAT",
  "SEAFOOD",
  "VEGETABLE",
  "STAPLE",
  "SEASONING",
  "BEVERAGE",
  "TABLEWARE",
  "EQUIPMENT",
  "PACKAGING",
] as const;
export type SubjectFood = (typeof subjectFood)[number];

/** ttl_class（4 值） */
export const ttlClass = ["SHORT", "MEDIUM", "LONG", "EVERGREEN"] as const;
export type TtlClass = (typeof ttlClass)[number];

// ── 词表元数据（zh 展示名 / def 定义 / 等价类 / 废弃链） ─────

export const actionMeta = {
  CUT: {
    zh: "切",
    def: "刀具分割食材",
    equivalenceClass: ["PREP"],
    deprecated: false,
    replacedBy: null,
  },
  WASH: {
    zh: "清洗",
    def: "水洗食材/器具",
    equivalenceClass: ["PREP", "HYGIENE"],
    deprecated: false,
    replacedBy: null,
  },
  MARINATE: {
    zh: "腌制",
    def: "加调料腌制静置",
    equivalenceClass: ["PREP"],
    deprecated: false,
    replacedBy: null,
  },
  STIR: {
    zh: "搅拌",
    def: "搅拌混合（馅料/面糊/饮品）",
    equivalenceClass: ["PREP"],
    deprecated: false,
    replacedBy: null,
  },
  POUR: {
    zh: "倒",
    def: "倾倒液体/浇汁",
    equivalenceClass: ["ASSEMBLE"],
    deprecated: false,
    replacedBy: null,
  },
  SPRINKLE: {
    zh: "撒",
    def: "撒放调料/葱花/芝麻等",
    equivalenceClass: ["ASSEMBLE"],
    deprecated: false,
    replacedBy: null,
  },
  SEASON: {
    zh: "调味",
    def: "加调味料动作（勺/壶）",
    equivalenceClass: ["ASSEMBLE"],
    deprecated: false,
    replacedBy: null,
  },
  WRAP: {
    zh: "包裹",
    def: "包制（包子/饺子/卷类）",
    equivalenceClass: ["ASSEMBLE"],
    deprecated: false,
    replacedBy: null,
  },
  ROLL: {
    zh: "擀卷",
    def: "擀制/卷制面食",
    equivalenceClass: ["ASSEMBLE"],
    deprecated: false,
    replacedBy: null,
  },
  KNEAD: {
    zh: "揉面",
    def: "揉制面团",
    equivalenceClass: ["PREP"],
    deprecated: false,
    replacedBy: null,
  },
  STIR_FRY: {
    zh: "翻炒",
    def: "锅中翻炒",
    equivalenceClass: ["COOK"],
    deprecated: false,
    replacedBy: null,
  },
  DEEP_FRY: {
    zh: "炸",
    def: "油炸烹饪",
    equivalenceClass: ["COOK"],
    deprecated: false,
    replacedBy: null,
  },
  STEAM: {
    zh: "蒸",
    def: "蒸制烹饪",
    equivalenceClass: ["COOK"],
    deprecated: false,
    replacedBy: null,
  },
  BOIL: {
    zh: "煮烫",
    def: "水煮/汆烫",
    equivalenceClass: ["COOK"],
    deprecated: false,
    replacedBy: null,
  },
  GRILL: {
    zh: "煎烤",
    def: "煎/烤/烙制",
    equivalenceClass: ["COOK"],
    deprecated: false,
    replacedBy: null,
  },
  SIMMER: {
    zh: "炖焖",
    def: "炖煮/焖制（汤类/卤味）",
    equivalenceClass: ["COOK"],
    deprecated: false,
    replacedBy: null,
  },
  PLATE: {
    zh: "摆盘",
    def: "装盘造型",
    equivalenceClass: ["PRESENT"],
    deprecated: false,
    replacedBy: null,
  },
  GARNISH: {
    zh: "点缀",
    def: "成品上加点缀物",
    equivalenceClass: ["PRESENT"],
    deprecated: false,
    replacedBy: null,
  },
  LIFT: {
    zh: "起锅端起",
    def: "起锅/端起成品展示",
    equivalenceClass: ["PRESENT"],
    deprecated: false,
    replacedBy: null,
  },
  OPEN_LID: {
    zh: "揭盖",
    def: "揭开锅盖/蒸笼（蒸汽释放瞬间）",
    equivalenceClass: ["PRESENT"],
    deprecated: false,
    replacedBy: null,
  },
  STEAM_RISE: {
    zh: "热气升腾",
    def: "无主体的热气/锅气画面（欲望触发物）",
    equivalenceClass: ["PRESENT"],
    deprecated: false,
    replacedBy: null,
  },
  SERVE: {
    zh: "上菜递出",
    def: "递送/上菜到桌",
    equivalenceClass: ["SERVICE"],
    deprecated: false,
    replacedBy: null,
  },
  PACK: {
    zh: "打包",
    def: "装盒/封袋打包",
    equivalenceClass: ["SERVICE"],
    deprecated: false,
    replacedBy: null,
  },
  TAKE_ORDER: {
    zh: "点单",
    def: "接单/推荐点单交互",
    equivalenceClass: ["SERVICE"],
    deprecated: false,
    replacedBy: null,
  },
  CHECKOUT: {
    zh: "收银结账",
    def: "结账/收款动作",
    equivalenceClass: ["SERVICE"],
    deprecated: false,
    replacedBy: null,
  },
  UNBOX: {
    zh: "验货拆箱",
    def: "进货验收/拆箱",
    equivalenceClass: ["SUPPLY"],
    deprecated: false,
    replacedBy: null,
  },
  WEIGH: {
    zh: "称重",
    def: "称量食材/成品",
    equivalenceClass: ["SUPPLY"],
    deprecated: false,
    replacedBy: null,
  },
  SMILE: {
    zh: "微笑",
    def: "人物微笑表情",
    equivalenceClass: ["REACTION"],
    deprecated: false,
    replacedBy: null,
  },
  WAVE: {
    zh: "招呼",
    def: "挥手/招呼手势",
    equivalenceClass: ["REACTION"],
    deprecated: false,
    replacedBy: null,
  },
  POINT: {
    zh: "指向",
    def: "手势指向主体（引导视线）",
    equivalenceClass: ["REACTION"],
    deprecated: false,
    replacedBy: null,
  },
  RECOMMEND: {
    zh: "推荐",
    def: "推荐/介绍手势与姿态",
    equivalenceClass: ["REACTION"],
    deprecated: false,
    replacedBy: null,
  },
  THUMBS_UP: {
    zh: "认可",
    def: "点赞/认可手势",
    equivalenceClass: ["REACTION"],
    deprecated: false,
    replacedBy: null,
  },
  EAT: {
    zh: "进食",
    def: "试吃/进食（反应类内容核心）",
    equivalenceClass: ["REACTION"],
    deprecated: false,
    replacedBy: null,
  },
  DRINK: {
    zh: "饮用",
    def: "饮用/品鉴",
    equivalenceClass: ["REACTION"],
    deprecated: false,
    replacedBy: null,
  },
  REACT_SURPRISE: {
    zh: "惊讶",
    def: "惊讶/满足等外显情绪反应",
    equivalenceClass: ["REACTION"],
    deprecated: false,
    replacedBy: null,
  },
  QUEUE: {
    zh: "排队等候",
    def: "顾客排队/候餐（热度证据）",
    equivalenceClass: ["SOCIAL"],
    deprecated: false,
    replacedBy: null,
  },
  WALK_THROUGH: {
    zh: "穿行",
    def: "人物在场景中走动（运镜跟随时也标注）",
    equivalenceClass: ["SOCIAL"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const audioRoleMeta = {
  VO: {
    zh: "口播",
    def: "主体叙事音频（TTS 或真人），决定 beat 时长下界",
    equivalenceClass: ["SPEECH"],
    deprecated: false,
    replacedBy: null,
  },
  SYNC: {
    zh: "同期声",
    def: "现场收音（环境声/操作声），增强真实感",
    equivalenceClass: ["AMBIENT"],
    deprecated: false,
    replacedBy: null,
  },
  SILENT: {
    zh: "静音",
    def: "无音频输出（BGM 由平台侧添加时使用，配合卡点标记）",
    equivalenceClass: ["AMBIENT"],
    deprecated: false,
    replacedBy: null,
  },
  SFX: {
    zh: "音效",
    def: "点缀性音效（切菜声/收银声），不承担叙事",
    equivalenceClass: ["AMBIENT"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const beatRoleMeta = {
  HOOK: {
    zh: "钩子",
    def: "前 3 秒内承担停留率职责的开口，必须制造信息差或冲突",
    equivalenceClass: ["OPENING"],
    deprecated: false,
    replacedBy: null,
  },
  CONTEXT: {
    zh: "语境",
    def: "交代人物/地点/时间等背景信息，为 PROOF 建立理解前提",
    equivalenceClass: ["BODY"],
    deprecated: false,
    replacedBy: null,
  },
  PROOF: {
    zh: "证据",
    def: "用可见画面证明主张（演示/对比/证言/资质/数据）",
    equivalenceClass: ["BODY"],
    deprecated: false,
    replacedBy: null,
  },
  CONTRAST: {
    zh: "对比",
    def: '呈现"没有对比就没有伤害"，正面回应 audience.objection',
    equivalenceClass: ["BODY"],
    deprecated: false,
    replacedBy: null,
  },
  OFFER: {
    zh: "主张",
    def: '给出具体的转化主张（价格/活动/权益），与 CTA 分工：OFFER 说"什么"，CTA 说"怎么做"',
    equivalenceClass: ["CLOSING"],
    deprecated: false,
    replacedBy: null,
  },
  CTA: {
    zh: "行动号召",
    def: "明确的下一步动作指令，通常在末尾",
    equivalenceClass: ["CLOSING"],
    deprecated: false,
    replacedBy: null,
  },
  BUMPER: {
    zh: "尾板",
    def: "品牌记忆板（店名/位置/slogan），帧数短、可复用",
    equivalenceClass: ["CLOSING"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const cameraMotionMeta = {
  STATIC: {
    zh: "固定",
    def: "机位不动（含手机支架固定），画面内运动仅来自主体",
    equivalenceClass: ["STABLE"],
    deprecated: false,
    replacedBy: null,
  },
  PUSH: {
    zh: "推",
    def: "向主体推近，制造聚焦/进入感；dir=IN",
    equivalenceClass: ["AXIAL"],
    deprecated: false,
    replacedBy: null,
  },
  PULL: {
    zh: "拉",
    def: "从主体拉远，交代环境；dir=OUT",
    equivalenceClass: ["AXIAL"],
    deprecated: false,
    replacedBy: null,
  },
  PAN: {
    zh: "摇",
    def: "机位不动水平转动；dir=LEFT/RIGHT",
    equivalenceClass: ["ROTATIONAL"],
    deprecated: false,
    replacedBy: null,
  },
  TILT: {
    zh: "俯仰",
    def: "机位不动垂直转动；dir=UP/DOWN",
    equivalenceClass: ["ROTATIONAL"],
    deprecated: false,
    replacedBy: null,
  },
  TRACK: {
    zh: "移",
    def: "机位平移跟随主体；dir=LEFT/RIGHT",
    equivalenceClass: ["LATERAL"],
    deprecated: false,
    replacedBy: null,
  },
  HANDHELD: {
    zh: "手持",
    def: "手持跟拍，允许轻微晃动（shake_score 阈值放宽）",
    equivalenceClass: ["LATERAL", "DYNAMIC"],
    deprecated: false,
    replacedBy: null,
  },
  ORBIT: {
    zh: "环绕",
    def: "围绕主体弧形运动",
    equivalenceClass: ["ROTATIONAL", "DYNAMIC"],
    deprecated: false,
    replacedBy: null,
  },
  WHIP: {
    zh: "甩",
    def: "快速甩镜转场，常接匹配剪辑",
    equivalenceClass: ["DYNAMIC", "TRANSITION"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const complianceRiskMeta = {
  AD_LAW_SUPERLATIVE: {
    zh: "广告法极限词",
    def: "最/第一/国家级等绝对化用语",
    equivalenceClass: ["AD_LAW"],
    deprecated: false,
    replacedBy: null,
  },
  AD_LAW_UNPROVEN_CLAIM: {
    zh: "无依据功效宣称",
    def: "未经证实的功效/效果宣称",
    equivalenceClass: ["AD_LAW"],
    deprecated: false,
    replacedBy: null,
  },
  MEDICAL_CLAIM: {
    zh: "医疗功效表述",
    def: "涉及治疗/预防疾病表述（食品高危）",
    equivalenceClass: ["AD_LAW", "CATEGORY"],
    deprecated: false,
    replacedBy: null,
  },
  FINANCIAL_PROMISE: {
    zh: "收益承诺",
    def: "投资回报类承诺表述",
    equivalenceClass: ["AD_LAW", "CATEGORY"],
    deprecated: false,
    replacedBy: null,
  },
  PRICE_FRAUD: {
    zh: "价格误导",
    def: "虚构原价/不实折扣",
    equivalenceClass: ["AD_LAW"],
    deprecated: false,
    replacedBy: null,
  },
  MISSING_QUALIFICATION: {
    zh: "类目资质缺失",
    def: "类目准入资质未验证（医疗/医美/金融等）",
    equivalenceClass: ["CATEGORY"],
    deprecated: false,
    replacedBy: null,
  },
  REQUIRED_DISCLAIMER_MISSING: {
    zh: "缺必需声明",
    def: '类目要求的声明缺失（如"效果因人而异"）',
    equivalenceClass: ["CATEGORY"],
    deprecated: false,
    replacedBy: null,
  },
  PORTRAIT_RIGHT: {
    zh: "肖像权",
    def: "未授权人脸出镜",
    equivalenceClass: ["IP_RIGHTS"],
    deprecated: false,
    replacedBy: null,
  },
  VOICE_RIGHT: {
    zh: "声音权",
    def: "声音克隆授权缺失或撤销",
    equivalenceClass: ["IP_RIGHTS"],
    deprecated: false,
    replacedBy: null,
  },
  TRADEMARK: {
    zh: "商标权",
    def: "第三方 logo/品牌标识露出",
    equivalenceClass: ["IP_RIGHTS"],
    deprecated: false,
    replacedBy: null,
  },
  MUSIC_LICENSE: {
    zh: "音乐版权",
    def: "音轨授权缺失/过期/超范围",
    equivalenceClass: ["IP_RIGHTS"],
    deprecated: false,
    replacedBy: null,
  },
  THIRD_PARTY_CONTENT: {
    zh: "三方内容",
    def: "未授权引用他人素材/画面",
    equivalenceClass: ["IP_RIGHTS"],
    deprecated: false,
    replacedBy: null,
  },
  AIGC_LABEL_REQUIRED: {
    zh: "AIGC 标识义务",
    def: "生成内容未按规定标识（显式+隐式）",
    equivalenceClass: ["AIGC_REG"],
    deprecated: false,
    replacedBy: null,
  },
  AI_FACE_MISUSE: {
    zh: "深度合成滥用",
    def: "生成人脸未显著标识/冒充真人",
    equivalenceClass: ["AIGC_REG"],
    deprecated: false,
    replacedBy: null,
  },
  FACT_STALE: {
    zh: "事实过期",
    def: "BrandKernel 事实字段过期未核验（价格/活动/店主变更）",
    equivalenceClass: ["FACTUAL"],
    deprecated: false,
    replacedBy: null,
  },
  FACT_UNVERIFIABLE: {
    zh: "事实不可验证",
    def: "主张无凭证且无法交叉验证",
    equivalenceClass: ["FACTUAL"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const copyFunctionMeta = {
  QUESTION_HOOK: {
    zh: "提问钩",
    def: "以疑问句开头制造信息差",
    equivalenceClass: ["HOOK"],
    deprecated: false,
    replacedBy: null,
  },
  NUMBER_HOOK: {
    zh: "数字钩",
    def: "以具体数字开场（年限/销量/价格）",
    equivalenceClass: ["HOOK"],
    deprecated: false,
    replacedBy: null,
  },
  COUNTERINTUITIVE_HOOK: {
    zh: "反常识钩",
    def: "挑战常识认知引发好奇",
    equivalenceClass: ["HOOK"],
    deprecated: false,
    replacedBy: null,
  },
  SCENE_HOOK: {
    zh: "场景带入钩",
    def: "描绘时间地点场景让目标客代入",
    equivalenceClass: ["HOOK"],
    deprecated: false,
    replacedBy: null,
  },
  RESULT_FIRST: {
    zh: "结果前置",
    def: "先给成品/结果再讲过程",
    equivalenceClass: ["HOOK", "DESIRE"],
    deprecated: false,
    replacedBy: null,
  },
  PAIN_CALLOUT: {
    zh: "痛点点名",
    def: "点名目标客群的具体困扰",
    equivalenceClass: ["CONTEXT"],
    deprecated: false,
    replacedBy: null,
  },
  ORIGIN_STORY: {
    zh: "来源故事",
    def: "食材/物料的溯源叙事",
    equivalenceClass: ["TRUST"],
    deprecated: false,
    replacedBy: null,
  },
  CRAFT_STORY: {
    zh: "工艺故事",
    def: "独家手艺/制作工艺叙事",
    equivalenceClass: ["TRUST"],
    deprecated: false,
    replacedBy: null,
  },
  PERSONA_STORY: {
    zh: "人格故事",
    def: "店主/店员的人格化叙事",
    equivalenceClass: ["TRUST"],
    deprecated: false,
    replacedBy: null,
  },
  TESTIMONY_QUOTE: {
    zh: "证言引用",
    def: "引用顾客原话评价",
    equivalenceClass: ["TRUST"],
    deprecated: false,
    replacedBy: null,
  },
  DATA_CITE: {
    zh: "数据引用",
    def: "引用可核验的经营数据",
    equivalenceClass: ["TRUST"],
    deprecated: false,
    replacedBy: null,
  },
  OBJECTION_RESPOND: {
    zh: "抗拒点回应",
    def: "正面回应受众顾虑（贵/远/慢）",
    equivalenceClass: ["CONTRAST"],
    deprecated: false,
    replacedBy: null,
  },
  COMPARISON: {
    zh: "对比句式",
    def: "我家 vs 别家 / 之前 vs 之后",
    equivalenceClass: ["CONTRAST"],
    deprecated: false,
    replacedBy: null,
  },
  SCARCITY: {
    zh: "限时限量",
    def: "时间/数量受限的稀缺表达（广告法高危，需断言检查）",
    equivalenceClass: ["CONVERSION"],
    deprecated: false,
    replacedBy: null,
  },
  OFFER_CLAIM: {
    zh: "权益主张",
    def: "具体价格/活动/权益说明",
    equivalenceClass: ["CONVERSION"],
    deprecated: false,
    replacedBy: null,
  },
  DIRECTION_CTA: {
    zh: "行动指令",
    def: "明确下一步动作（到店/私信/点团购）",
    equivalenceClass: ["CONVERSION"],
    deprecated: false,
    replacedBy: null,
  },
  LOCATION_CUE: {
    zh: "位置提示",
    def: "位置/营业时间等到达信息",
    equivalenceClass: ["CONVERSION", "BRAND"],
    deprecated: false,
    replacedBy: null,
  },
  SLOGAN: {
    zh: "品牌口号",
    def: "店铺 slogan 或品牌句",
    equivalenceClass: ["BRAND"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const defectTypeMeta = {
  BLURRY: {
    zh: "画面模糊",
    def: "清晰度低于阈值（laplacian_var）",
    equivalenceClass: ["L0_TECHNICAL"],
    deprecated: false,
    replacedBy: null,
  },
  SHAKE: {
    zh: "抖动",
    def: "运动抖动超标（optical_flow）",
    equivalenceClass: ["L0_TECHNICAL"],
    deprecated: false,
    replacedBy: null,
  },
  OVEREXPOSED: {
    zh: "过曝",
    def: "高光溢出占比超标",
    equivalenceClass: ["L0_TECHNICAL"],
    deprecated: false,
    replacedBy: null,
  },
  UNDEREXPOSED: {
    zh: "欠曝",
    def: "暗部死黑占比超标",
    equivalenceClass: ["L0_TECHNICAL"],
    deprecated: false,
    replacedBy: null,
  },
  FLICKER: {
    zh: "频闪",
    def: "帧间亮度闪烁超标（flicker_index）",
    equivalenceClass: ["L0_TECHNICAL"],
    deprecated: false,
    replacedBy: null,
  },
  BLACK_FRAME: {
    zh: "黑帧",
    def: "存在黑帧区间（blackdetect）",
    equivalenceClass: ["L0_TECHNICAL"],
    deprecated: false,
    replacedBy: null,
  },
  FREEZE_FRAME: {
    zh: "画面冻结",
    def: "画面静止区间超标（freezedetect）",
    equivalenceClass: ["L0_TECHNICAL"],
    deprecated: false,
    replacedBy: null,
  },
  AUDIO_CLIPPING: {
    zh: "爆音",
    def: "真峰值超过 0dBTP",
    equivalenceClass: ["L0_AUDIO"],
    deprecated: false,
    replacedBy: null,
  },
  AUDIO_TOO_QUIET: {
    zh: "音量过低",
    def: "响度低于目标 LUFS 下界",
    equivalenceClass: ["L0_AUDIO"],
    deprecated: false,
    replacedBy: null,
  },
  NOISY_AUDIO: {
    zh: "音频噪声",
    def: "信噪比低于阈值",
    equivalenceClass: ["L0_AUDIO"],
    deprecated: false,
    replacedBy: null,
  },
  SILENT_AUDIO: {
    zh: "无音频",
    def: "声轨为空但声明需同期声",
    equivalenceClass: ["L0_AUDIO"],
    deprecated: false,
    replacedBy: null,
  },
  RESOLUTION_LOW: {
    zh: "分辨率不足",
    def: "低于 1080x1920 要求",
    equivalenceClass: ["L0_TECHNICAL"],
    deprecated: false,
    replacedBy: null,
  },
  ASPECT_MISMATCH: {
    zh: "画幅不符",
    def: "非竖版 9:16 源",
    equivalenceClass: ["L0_TECHNICAL"],
    deprecated: false,
    replacedBy: null,
  },
  SUBJECT_MISSING: {
    zh: "主体缺失",
    def: "要求的主体未检出（L1 判定题）",
    equivalenceClass: ["L1_CONTENT"],
    deprecated: false,
    replacedBy: null,
  },
  SUBJECT_TOO_SMALL: {
    zh: "主体过小",
    def: "主体面积占比低于 spec 下界",
    equivalenceClass: ["L1_CONTENT"],
    deprecated: false,
    replacedBy: null,
  },
  SUBJECT_TRUNCATED: {
    zh: "主体截断",
    def: "主体越出画面/裁切后断头断尾",
    equivalenceClass: ["L1_CONTENT"],
    deprecated: false,
    replacedBy: null,
  },
  WRONG_SHOT_TYPE: {
    zh: "镜位不符",
    def: "实拍镜位与制作令 spec 不符",
    equivalenceClass: ["L1_CONTENT"],
    deprecated: false,
    replacedBy: null,
  },
  WRONG_MOTION: {
    zh: "运镜不符",
    def: "运镜类型/方向与 spec 不符",
    equivalenceClass: ["L1_CONTENT"],
    deprecated: false,
    replacedBy: null,
  },
  BAD_FRAMING: {
    zh: "构图越界",
    def: "主体/文字越过安全区或画面边缘",
    equivalenceClass: ["L1_CONTENT"],
    deprecated: false,
    replacedBy: null,
  },
  NEGATIVE_SPACE_MISSING: {
    zh: "无可用负空间",
    def: "画面无可安放字幕的连续低纹理区域",
    equivalenceClass: ["L1_CONTENT"],
    deprecated: false,
    replacedBy: null,
  },
  OBSTRUCTED: {
    zh: "遮挡",
    def: "前景异物遮挡主体",
    equivalenceClass: ["L1_CONTENT"],
    deprecated: false,
    replacedBy: null,
  },
  BACKGROUND_CLUTTER: {
    zh: "背景杂乱",
    def: "背景干扰主体辨识（含杂乱后厨/无关人员）",
    equivalenceClass: ["L1_CONTENT"],
    deprecated: false,
    replacedBy: null,
  },
  HANDLES_MISSING: {
    zh: "首尾无余量",
    def: "动作开始/结束无 handles 余量，无法转场",
    equivalenceClass: ["L1_CONTENT"],
    deprecated: false,
    replacedBy: null,
  },
  DURATION_SHORT: {
    zh: "时长不足",
    def: "素材可用时长低于 beat duration_range 下界",
    equivalenceClass: ["L1_CONTENT"],
    deprecated: false,
    replacedBy: null,
  },
  WRONG_SCENE: {
    zh: "场景不符",
    def: "实拍场景与 spec.scene 不符",
    equivalenceClass: ["L1_CONTENT"],
    deprecated: false,
    replacedBy: null,
  },
  LIPSYNC_OFF: {
    zh: "口型不同步",
    def: "LSE-C/LSE-D 超标（生成物）",
    equivalenceClass: ["L2_GENERATED"],
    deprecated: false,
    replacedBy: null,
  },
  FACE_WARP: {
    zh: "面部畸变",
    def: "生成面部结构异常",
    equivalenceClass: ["L2_GENERATED"],
    deprecated: false,
    replacedBy: null,
  },
  HAND_WARP: {
    zh: "手部畸变",
    def: "生成手部结构异常",
    equivalenceClass: ["L2_GENERATED"],
    deprecated: false,
    replacedBy: null,
  },
  TEXT_WARP: {
    zh: "文字畸变",
    def: "画面内生成文字乱码/变形",
    equivalenceClass: ["L2_GENERATED"],
    deprecated: false,
    replacedBy: null,
  },
  TEMPORAL_WARP: {
    zh: "时序扭曲",
    def: "帧间运动不连贯（temporal_warp_error）",
    equivalenceClass: ["L2_GENERATED"],
    deprecated: false,
    replacedBy: null,
  },
  PLASTIC_LOOK: {
    zh: "塑料感",
    def: '无参考质量模型判定"AI 感"过强（DOVER/FastVQA）',
    equivalenceClass: ["L2_GENERATED"],
    deprecated: false,
    replacedBy: null,
  },
  IDENTITY_DRIFT: {
    zh: "身份漂移",
    def: "生成人物与目标身份相似度不足（face_identity_sim）",
    equivalenceClass: ["L2_GENERATED"],
    deprecated: false,
    replacedBy: null,
  },
  THIRD_PARTY_FACE: {
    zh: "第三方人脸",
    def: "画面含未授权出镜的第三人",
    equivalenceClass: ["L3_COMPLIANCE"],
    deprecated: false,
    replacedBy: null,
  },
  THIRD_PARTY_LOGO: {
    zh: "第三方标识",
    def: "画面含竞品/第三方 logo、招牌、车牌",
    equivalenceClass: ["L3_COMPLIANCE"],
    deprecated: false,
    replacedBy: null,
  },
  BANNED_TERM: {
    zh: "违禁表达",
    def: "文案/OCR 含违禁词或隐含功效宣称",
    equivalenceClass: ["L3_COMPLIANCE"],
    deprecated: false,
    replacedBy: null,
  },
  CLAIM_WITHOUT_PROOF: {
    zh: "无证据宣称",
    def: "主张无可视觉验证的证据支撑",
    equivalenceClass: ["L3_COMPLIANCE"],
    deprecated: false,
    replacedBy: null,
  },
  LICENSE_MUSIC_MISSING: {
    zh: "音乐无授权",
    def: "音轨缺少有效授权凭证或已过期",
    equivalenceClass: ["L3_COMPLIANCE"],
    deprecated: false,
    replacedBy: null,
  },
  AIGC_LABEL_MISSING: {
    zh: "缺 AIGC 标识",
    def: "缺少显式/隐式 AIGC 标识（GB 45438-2025）",
    equivalenceClass: ["L3_COMPLIANCE"],
    deprecated: false,
    replacedBy: null,
  },
  PORTRAIT_AUTH_MISSING: {
    zh: "缺肖像授权",
    def: "出镜人授权缺失或已撤销",
    equivalenceClass: ["L3_COMPLIANCE"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const moodMeta = {
  WARM: {
    zh: "温暖",
    def: "暖光/烟火气/家常感",
    equivalenceClass: ["POSITIVE"],
    deprecated: false,
    replacedBy: null,
  },
  ENERGETIC: {
    zh: "热闹",
    def: "快节奏/人群/市井喧闹",
    equivalenceClass: ["POSITIVE"],
    deprecated: false,
    replacedBy: null,
  },
  COZY: {
    zh: "惬意",
    def: "慢节奏/私密/治愈感",
    equivalenceClass: ["POSITIVE"],
    deprecated: false,
    replacedBy: null,
  },
  FRESH: {
    zh: "清新",
    def: "冷调/明亮/食材本味感",
    equivalenceClass: ["POSITIVE"],
    deprecated: false,
    replacedBy: null,
  },
  APPETIZING: {
    zh: "馋人",
    def: "高饱和/特写食欲诱发",
    equivalenceClass: ["POSITIVE"],
    deprecated: false,
    replacedBy: null,
  },
  PROFESSIONAL: {
    zh: "专业",
    def: "工艺流程/匠心/秩序感",
    equivalenceClass: ["NEUTRAL"],
    deprecated: false,
    replacedBy: null,
  },
  PLAYFUL: {
    zh: "俏皮",
    def: "跳剪/表情包/轻快配乐",
    equivalenceClass: ["POSITIVE"],
    deprecated: false,
    replacedBy: null,
  },
  CALM: {
    zh: "安静",
    def: "静态构图/环境音/留白",
    equivalenceClass: ["NEUTRAL"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const negativeSpaceMeta = {
  TOP: {
    zh: "顶部",
    def: "画面上 1/3 连续空白",
    equivalenceClass: ["LAYOUT"],
    deprecated: false,
    replacedBy: null,
  },
  BOTTOM: {
    zh: "底部",
    def: "画面下 1/3 连续空白",
    equivalenceClass: ["LAYOUT"],
    deprecated: false,
    replacedBy: null,
  },
  LEFT: {
    zh: "左侧",
    def: "画面左 1/3 连续空白",
    equivalenceClass: ["LAYOUT"],
    deprecated: false,
    replacedBy: null,
  },
  RIGHT: {
    zh: "右侧",
    def: "画面右 1/3 连续空白",
    equivalenceClass: ["LAYOUT"],
    deprecated: false,
    replacedBy: null,
  },
  NONE: {
    zh: "无",
    def: "无满足面积阈值的空白区（字幕只能压画面）",
    equivalenceClass: ["LAYOUT"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const overlayIntentMeta = {
  EMPHASIZE_NUMBER: {
    zh: "强调数字",
    def: "放大关键数字（价格/年限/销量）",
    equivalenceClass: ["EMPHASIS"],
    deprecated: false,
    replacedBy: null,
  },
  EMPHASIZE_KEYWORD: {
    zh: "强调关键词",
    def: "高亮文案关键词",
    equivalenceClass: ["EMPHASIS"],
    deprecated: false,
    replacedBy: null,
  },
  KARAOKE_CAPTION: {
    zh: "逐字字幕",
    def: "词级同步字幕（依赖 word_timings）",
    equivalenceClass: ["CAPTION"],
    deprecated: false,
    replacedBy: null,
  },
  STATIC_CAPTION: {
    zh: "静态字幕",
    def: "整句字幕块",
    equivalenceClass: ["CAPTION"],
    deprecated: false,
    replacedBy: null,
  },
  ANNOTATE_PART: {
    zh: "标注部位",
    def: "指向画面部位/部件的标注",
    equivalenceClass: ["ANNOTATE"],
    deprecated: false,
    replacedBy: null,
  },
  ANNOTATE_PROOF: {
    zh: "标注证据",
    def: "为证照/检测报告等证据加注",
    equivalenceClass: ["ANNOTATE", "TRUST"],
    deprecated: false,
    replacedBy: null,
  },
  PROGRESS_STEPS: {
    zh: "步骤进度",
    def: "工艺步骤进度条",
    equivalenceClass: ["STRUCTURE"],
    deprecated: false,
    replacedBy: null,
  },
  COUNTDOWN: {
    zh: "倒计时",
    def: "活动倒计时（配 SCARCITY 文案）",
    equivalenceClass: ["STRUCTURE", "CONVERSION"],
    deprecated: false,
    replacedBy: null,
  },
  PRICE_TAG: {
    zh: "价格牌",
    def: "价格/团购价标牌",
    equivalenceClass: ["CONVERSION"],
    deprecated: false,
    replacedBy: null,
  },
  OFFER_BADGE: {
    zh: "权益角标",
    def: "活动/权益角标",
    equivalenceClass: ["CONVERSION"],
    deprecated: false,
    replacedBy: null,
  },
  LOCATION_CARD: {
    zh: "位置卡片",
    def: "店名+位置+营业时间卡片",
    equivalenceClass: ["CONVERSION", "BRAND"],
    deprecated: false,
    replacedBy: null,
  },
  LOGO_WATERMARK: {
    zh: "品牌水印",
    def: "店标水印（安全区常驻）",
    equivalenceClass: ["BRAND"],
    deprecated: false,
    replacedBy: null,
  },
  AIGC_DISCLOSURE: {
    zh: "AIGC 标识",
    def: "合规显式标识（ComplianceGate 强制注入，禁止 StyleTheme 覆盖）",
    equivalenceClass: ["COMPLIANCE"],
    deprecated: false,
    replacedBy: null,
  },
  SUBTITLE_FOREIGN: {
    zh: "译制字幕",
    def: "外语字幕轨（预留）",
    equivalenceClass: ["CAPTION"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const proofTypeMeta = {
  LIVE_DEMO: {
    zh: "现场演示",
    def: "拍摄过程本身作为证据（现场切配/现炒/现做）",
    equivalenceClass: ["PROCESS"],
    deprecated: false,
    replacedBy: null,
  },
  CUSTOMER_TESTIMONY: {
    zh: "顾客证言",
    def: "真实顾客出镜评价（需肖像授权）",
    equivalenceClass: ["SOCIAL"],
    deprecated: false,
    replacedBy: null,
  },
  QUALIFICATION: {
    zh: "资质证书",
    def: "证照/检测报告/授权书等文件画面",
    equivalenceClass: ["DOCUMENT"],
    deprecated: false,
    replacedBy: null,
  },
  DATA: {
    zh: "数据",
    def: "可核验的数字（销量/年限/复购率），来源需可追溯",
    equivalenceClass: ["DOCUMENT"],
    deprecated: false,
    replacedBy: null,
  },
  BEFORE_AFTER: {
    zh: "前后对比",
    def: "同主体处理前后对比（注意广告法风险，禁止夸大）",
    equivalenceClass: ["CONTRAST"],
    deprecated: false,
    replacedBy: null,
  },
  SOURCE_TRACE: {
    zh: "溯源",
    def: "食材/物料来源的现场证据（进货单/农场/冷链）",
    equivalenceClass: ["DOCUMENT", "PROCESS"],
    deprecated: false,
    replacedBy: null,
  },
  CRAFT_DETAIL: {
    zh: "工艺细节",
    def: "独家手艺/工艺的细节特写",
    equivalenceClass: ["PROCESS"],
    deprecated: false,
    replacedBy: null,
  },
  SCENE_ATMOSPHERE: {
    zh: "现场氛围",
    def: "排队/满座/出餐节奏等现场热度画面",
    equivalenceClass: ["SOCIAL"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const remedyActionMeta = {
  RESHOOT: {
    zh: "重拍",
    def: "重新拍摄该镜头（返修首选，配构图示意图与反例图）",
    equivalenceClass: ["MANUAL"],
    deprecated: false,
    replacedBy: null,
  },
  REGENERATE: {
    zh: "重新生成",
    def: "重新生成该生成物（换 seed/降语速）",
    equivalenceClass: ["AUTO_RETRY"],
    deprecated: false,
    replacedBy: null,
  },
  RE_CROP: {
    zh: "重新裁切",
    def: "调整裁切窗口重新构图（含自动重定位 auto_crop_recenter）",
    equivalenceClass: ["AUTO_FIX"],
    deprecated: false,
    replacedBy: null,
  },
  RECOLOR: {
    zh: "调色",
    def: "曝光/色彩修正（LUT/曲线）",
    equivalenceClass: ["AUTO_FIX"],
    deprecated: false,
    replacedBy: null,
  },
  AUDIO_FIX: {
    zh: "音频修复",
    def: "降噪/增益/补录",
    equivalenceClass: ["AUTO_FIX", "MANUAL"],
    deprecated: false,
    replacedBy: null,
  },
  REPLACE_SHOT: {
    zh: "换镜头",
    def: "用素材池中其他候选 shot 替换",
    equivalenceClass: ["AUTO_FIX"],
    deprecated: false,
    replacedBy: null,
  },
  TRIM: {
    zh: "裁剪时长",
    def: "调整入出点",
    equivalenceClass: ["AUTO_FIX"],
    deprecated: false,
    replacedBy: null,
  },
  SPEED_ADJUST: {
    zh: "变速",
    def: "调整播放速度（上限 1.15x，工艺参数见 craft_params）",
    equivalenceClass: ["AUTO_FIX"],
    deprecated: false,
    replacedBy: null,
  },
  REWRITE_COPY: {
    zh: "改写文案",
    def: "绕开违禁表达/修正事实性错误后重写",
    equivalenceClass: ["AUTO_RETRY"],
    deprecated: false,
    replacedBy: null,
  },
  MUTE_AUDIO: {
    zh: "静音处理",
    def: "去除问题音轨（改走卡点标记模式）",
    equivalenceClass: ["AUTO_FIX"],
    deprecated: false,
    replacedBy: null,
  },
  BLUR_MASK: {
    zh: "打码",
    def: "对第三方人脸/logo 做局部模糊或贴图遮盖",
    equivalenceClass: ["AUTO_FIX", "MANUAL"],
    deprecated: false,
    replacedBy: null,
  },
  ADD_DISCLAIMER: {
    zh: "补声明",
    def: '补必需声明（如"效果因人而异"）',
    equivalenceClass: ["AUTO_FIX"],
    deprecated: false,
    replacedBy: null,
  },
  ADD_LABEL: {
    zh: "补标识",
    def: "补 AIGC 显式/隐式标识",
    equivalenceClass: ["AUTO_FIX"],
    deprecated: false,
    replacedBy: null,
  },
  RE_ORDER: {
    zh: "重排",
    def: "调整 beat/clip 顺序",
    equivalenceClass: ["AUTO_FIX"],
    deprecated: false,
    replacedBy: null,
  },
  REJECT_SOURCE: {
    zh: "拒收素材",
    def: "素材不可修复（黑帧/损坏/分辨率不足），报废不入库",
    equivalenceClass: ["AUTO_FIX"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const sceneFoodMeta = {
  STOREFRONT: {
    zh: "门头",
    def: "店铺正面外观与招牌",
    equivalenceClass: ["EXTERNAL"],
    deprecated: false,
    replacedBy: null,
  },
  ENTRANCE: {
    zh: "出入口",
    def: "进出通道、迎宾位",
    equivalenceClass: ["EXTERNAL", "TRANSIT"],
    deprecated: false,
    replacedBy: null,
  },
  NEIGHBORHOOD: {
    zh: "社区周边",
    def: "店铺所在街区环境（通勤人流/邻里氛围）",
    equivalenceClass: ["EXTERNAL"],
    deprecated: false,
    replacedBy: null,
  },
  OUTDOOR_SEATING: {
    zh: "外摆区",
    def: "户外座位区",
    equivalenceClass: ["EXTERNAL", "FRONT_OF_HOUSE"],
    deprecated: false,
    replacedBy: null,
  },
  COUNTER: {
    zh: "前台",
    def: "收银/点单/出餐前台",
    equivalenceClass: ["FRONT_OF_HOUSE"],
    deprecated: false,
    replacedBy: null,
  },
  DELIVERY_COUNTER: {
    zh: "外卖档口",
    def: "外卖取餐与打包区",
    equivalenceClass: ["FRONT_OF_HOUSE"],
    deprecated: false,
    replacedBy: null,
  },
  DINING_AREA: {
    zh: "堂食区",
    def: "顾客用餐区域",
    equivalenceClass: ["FRONT_OF_HOUSE"],
    deprecated: false,
    replacedBy: null,
  },
  PRIVATE_ROOM: {
    zh: "包间",
    def: "独立包房",
    equivalenceClass: ["FRONT_OF_HOUSE"],
    deprecated: false,
    replacedBy: null,
  },
  OPEN_KITCHEN: {
    zh: "明档",
    def: "顾客可见的开放操作档口",
    equivalenceClass: ["BACK_OF_HOUSE", "FRONT_OF_HOUSE"],
    deprecated: false,
    replacedBy: null,
  },
  KITCHEN: {
    zh: "后厨",
    def: "封闭厨房（炉灶/炒锅区）",
    equivalenceClass: ["BACK_OF_HOUSE"],
    deprecated: false,
    replacedBy: null,
  },
  PREP_STATION: {
    zh: "备餐台",
    def: "切配/组装/摆盘操作台",
    equivalenceClass: ["BACK_OF_HOUSE"],
    deprecated: false,
    replacedBy: null,
  },
  WASH_STATION: {
    zh: "清洗区",
    def: "食材清洗/餐具洗消区",
    equivalenceClass: ["BACK_OF_HOUSE"],
    deprecated: false,
    replacedBy: null,
  },
  STORAGE: {
    zh: "仓储区",
    def: "冷库/货架/物料存储",
    equivalenceClass: ["BACK_OF_HOUSE"],
    deprecated: false,
    replacedBy: null,
  },
  SUPPLIER_ARRIVAL: {
    zh: "进货到货",
    def: "收货/验货现场（清晨进货场景）",
    equivalenceClass: ["BACK_OF_HOUSE", "TRANSIT"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const seasonMeta = {
  ALL: {
    zh: "全季",
    def: "全年可用（默认值）",
    equivalenceClass: ["EVERGREEN"],
    deprecated: false,
    replacedBy: null,
  },
  SPRING: {
    zh: "春",
    def: "3–5 月（含春季时令食材/氛围）",
    equivalenceClass: ["SEASONAL"],
    deprecated: false,
    replacedBy: null,
  },
  SUMMER: {
    zh: "夏",
    def: "6–8 月（冷饮/夜市/冰品）",
    equivalenceClass: ["SEASONAL"],
    deprecated: false,
    replacedBy: null,
  },
  AUTUMN: {
    zh: "秋",
    def: "9–11 月（秋季时令/贴秋膘）",
    equivalenceClass: ["SEASONAL"],
    deprecated: false,
    replacedBy: null,
  },
  WINTER: {
    zh: "冬",
    def: "12–2 月（火锅/热饮/年末）",
    equivalenceClass: ["SEASONAL"],
    deprecated: false,
    replacedBy: null,
  },
  FESTIVAL: {
    zh: "节庆",
    def: "特定节庆窗口（春节/中秋等，配 campaign 绑定）",
    equivalenceClass: ["SEASONAL", "EVENT"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const shotTypeMeta = {
  EXTREME_CLOSEUP: {
    zh: "大特写",
    def: "主体占画面 >70%，用于质感/细节",
    equivalenceClass: ["DETAIL"],
    deprecated: false,
    replacedBy: null,
  },
  CLOSEUP: {
    zh: "特写",
    def: "主体占画面 30%–70%，面部或单一主体充满视觉中心",
    equivalenceClass: ["DETAIL", "FACE"],
    deprecated: false,
    replacedBy: null,
  },
  MEDIUM: {
    zh: "中景",
    def: "主体腰部以上或操作台面全貌，动作可辨认",
    equivalenceClass: ["SUBJECT"],
    deprecated: false,
    replacedBy: null,
  },
  WIDE: {
    zh: "全景",
    def: "环境与主体关系完整可见，交代场所",
    equivalenceClass: ["CONTEXT", "ESTABLISHING"],
    deprecated: false,
    replacedBy: null,
  },
  OTS: {
    zh: "过肩/第一视角",
    def: "过肩或第一视角，制造代入感",
    equivalenceClass: ["SUBJECT", "POV"],
    deprecated: false,
    replacedBy: null,
  },
  TABLETOP: {
    zh: "俯拍平铺",
    def: "垂直俯拍桌面，适合成品/食材平铺陈列",
    equivalenceClass: ["DETAIL", "PRODUCT"],
    deprecated: false,
    replacedBy: null,
  },
  POV: {
    zh: "主观视角",
    def: "模拟观众视角（递给 viewer/端起碗），强代入",
    equivalenceClass: ["POV"],
    deprecated: false,
    replacedBy: null,
  },
  INSERT: {
    zh: "插入镜头",
    def: "补充细节的切入镜头（价签/手部动作/成品切面）",
    equivalenceClass: ["DETAIL"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const subjectFoodMeta = {
  OWNER: {
    zh: "店主",
    def: "店主本人出镜（人格化叙事核心主体）",
    equivalenceClass: ["PERSON", "STAFF_ROLE"],
    deprecated: false,
    replacedBy: null,
  },
  CHEF: {
    zh: "厨师",
    def: "后厨烹饪人员",
    equivalenceClass: ["PERSON", "STAFF_ROLE"],
    deprecated: false,
    replacedBy: null,
  },
  STAFF: {
    zh: "店员",
    def: "前场服务人员",
    equivalenceClass: ["PERSON", "STAFF_ROLE"],
    deprecated: false,
    replacedBy: null,
  },
  CUSTOMER: {
    zh: "顾客",
    def: "到店顾客（出镜需肖像合规检查）",
    equivalenceClass: ["PERSON"],
    deprecated: false,
    replacedBy: null,
  },
  REGULAR_CUSTOMER: {
    zh: "熟客",
    def: "可识别的常客（证言类内容主体）",
    equivalenceClass: ["PERSON"],
    deprecated: false,
    replacedBy: null,
  },
  COURIER: {
    zh: "骑手",
    def: "外卖配送人员",
    equivalenceClass: ["PERSON"],
    deprecated: false,
    replacedBy: null,
  },
  HANDS: {
    zh: "手部",
    def: "手部动作特写主体（不计入人数，规避肖像问题）",
    equivalenceClass: ["PERSON_PART"],
    deprecated: false,
    replacedBy: null,
  },
  SIGNAGE: {
    zh: "招牌",
    def: "店名字号/灯箱/门头牌匾",
    equivalenceClass: ["OBJECT", "BRAND_ASSET"],
    deprecated: false,
    replacedBy: null,
  },
  MENU_BOARD: {
    zh: "菜单牌",
    def: "菜单/价目表/灯箱菜单",
    equivalenceClass: ["OBJECT", "BRAND_ASSET"],
    deprecated: false,
    replacedBy: null,
  },
  QUALIFICATION_CERT: {
    zh: "证照",
    def: "营业执照/食品经营许可等资质文件",
    equivalenceClass: ["DOCUMENT"],
    deprecated: false,
    replacedBy: null,
  },
  RECEIPT: {
    zh: "小票价签",
    def: "收银小票、手写价签",
    equivalenceClass: ["DOCUMENT"],
    deprecated: false,
    replacedBy: null,
  },
  DISH_FINISHED: {
    zh: "成品菜",
    def: "制作完成的出品",
    equivalenceClass: ["FOOD", "PRODUCT"],
    deprecated: false,
    replacedBy: null,
  },
  DISH_PLATING: {
    zh: "摆盘出品",
    def: "摆盘/装盘过程中的出品",
    equivalenceClass: ["FOOD", "PRODUCT"],
    deprecated: false,
    replacedBy: null,
  },
  INGREDIENT_RAW: {
    zh: "生鲜食材",
    def: "未加工的原始食材",
    equivalenceClass: ["FOOD", "INGREDIENT"],
    deprecated: false,
    replacedBy: null,
  },
  INGREDIENT_PREPPED: {
    zh: "半成品",
    def: "已切配/腌制的加工中食材",
    equivalenceClass: ["FOOD", "INGREDIENT"],
    deprecated: false,
    replacedBy: null,
  },
  MEAT: {
    zh: "肉类",
    def: "生鲜肉类食材",
    equivalenceClass: ["FOOD", "INGREDIENT"],
    deprecated: false,
    replacedBy: null,
  },
  SEAFOOD: {
    zh: "水产",
    def: "活鲜/冰鲜水产",
    equivalenceClass: ["FOOD", "INGREDIENT"],
    deprecated: false,
    replacedBy: null,
  },
  VEGETABLE: {
    zh: "蔬菜",
    def: "蔬菜类食材",
    equivalenceClass: ["FOOD", "INGREDIENT"],
    deprecated: false,
    replacedBy: null,
  },
  STAPLE: {
    zh: "主食",
    def: "米面/包子/饺子等主食",
    equivalenceClass: ["FOOD"],
    deprecated: false,
    replacedBy: null,
  },
  SEASONING: {
    zh: "调料",
    def: "调味料及其使用瞬间",
    equivalenceClass: ["FOOD", "INGREDIENT"],
    deprecated: false,
    replacedBy: null,
  },
  BEVERAGE: {
    zh: "饮品",
    def: "现制饮品/酒水",
    equivalenceClass: ["FOOD", "PRODUCT"],
    deprecated: false,
    replacedBy: null,
  },
  TABLEWARE: {
    zh: "餐具",
    def: "碗碟筷杯等器皿",
    equivalenceClass: ["OBJECT"],
    deprecated: false,
    replacedBy: null,
  },
  EQUIPMENT: {
    zh: "设备器具",
    def: "炉灶/蒸箱/料理机等设备",
    equivalenceClass: ["OBJECT"],
    deprecated: false,
    replacedBy: null,
  },
  PACKAGING: {
    zh: "餐盒包装",
    def: "外卖餐盒/打包袋",
    equivalenceClass: ["OBJECT", "PRODUCT"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

export const ttlClassMeta = {
  SHORT: {
    zh: "短时效",
    def: "默认 30 天（活动氛围/时事相关）",
    equivalenceClass: ["DECAYING"],
    deprecated: false,
    replacedBy: null,
  },
  MEDIUM: {
    zh: "中时效",
    def: "默认 90 天（当季菜品/着装场景）",
    equivalenceClass: ["DECAYING"],
    deprecated: false,
    replacedBy: null,
  },
  LONG: {
    zh: "长时效",
    def: "默认 180 天（工艺/环境/设备）",
    equivalenceClass: ["DECAYING"],
    deprecated: false,
    replacedBy: null,
  },
  EVERGREEN: {
    zh: "常青",
    def: "默认 365 天（门头/证照/人格出镜，仍需年检式复核）",
    equivalenceClass: ["EVERGREEN"],
    deprecated: false,
    replacedBy: null,
  },
} as const;

// ── 注册表（按 VocabName 泛型取用，供运行期校验/查询助手） ────

export type VocabMetaEntry = {
  readonly zh: string;
  readonly def: string;
  readonly equivalenceClass: readonly string[];
  readonly deprecated: boolean;
  readonly replacedBy: string | null;
};

export const VOCAB_IDS = {
  action: action,
  audio_role: audioRole,
  beat_role: beatRole,
  camera_motion: cameraMotion,
  compliance_risk: complianceRisk,
  copy_function: copyFunction,
  defect_type: defectType,
  mood: mood,
  negative_space: negativeSpace,
  overlay_intent: overlayIntent,
  proof_type: proofType,
  remedy_action: remedyAction,
  "scene.food": sceneFood,
  season: season,
  shot_type: shotType,
  "subject.food": subjectFood,
  ttl_class: ttlClass,
} satisfies Readonly<Record<VocabName, readonly string[]>>;

export const VOCAB_META = {
  action: actionMeta,
  audio_role: audioRoleMeta,
  beat_role: beatRoleMeta,
  camera_motion: cameraMotionMeta,
  compliance_risk: complianceRiskMeta,
  copy_function: copyFunctionMeta,
  defect_type: defectTypeMeta,
  mood: moodMeta,
  negative_space: negativeSpaceMeta,
  overlay_intent: overlayIntentMeta,
  proof_type: proofTypeMeta,
  remedy_action: remedyActionMeta,
  "scene.food": sceneFoodMeta,
  season: seasonMeta,
  shot_type: shotTypeMeta,
  "subject.food": subjectFoodMeta,
  ttl_class: ttlClassMeta,
} satisfies Readonly<
  Record<VocabName, Readonly<Record<string, VocabMetaEntry>>>
>;
